// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WarehouseManagerServer.Models.DTOs;

#nullable disable

namespace WarehouseManagerServer.Migrations
{
    [DbContext(typeof(WarehouseContext))]
    partial class WarehouseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UserWarehouse", b =>
                {
                    b.Property<int>("UsersUserId")
                        .HasColumnType("integer");

                    b.Property<int>("WarehousesWarehouseId")
                        .HasColumnType("integer");

                    b.HasKey("UsersUserId", "WarehousesWarehouseId");

                    b.HasIndex("WarehousesWarehouseId");

                    b.ToTable("UserWarehouses", (string)null);
                });

            modelBuilder.Entity("WarehouseManagerServer.Models.Entities.EmailVerification", b =>
                {
                    b.Property<int>("CodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("code_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CodeId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("code");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expire_at");

                    b.Property<string>("VerificationType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("verification_type");

                    b.HasKey("CodeId")
                        .HasName("email_verification_pkey");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("email_verification", (string)null);
                });

            modelBuilder.Entity("WarehouseManagerServer.Models.Entities.History", b =>
                {
                    b.Property<int>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("history_id")
                        .HasAnnotation("Relational:JsonPropertyName", "history_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HistoryId"));

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action_type")
                        .HasAnnotation("Relational:JsonPropertyName", "action_type");

                    b.Property<DateTime>("Date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP")
                        .HasAnnotation("Relational:JsonPropertyName", "date");

                    b.Property<int?>("ProductId")
                        .HasColumnType("integer");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("product_name")
                        .HasAnnotation("Relational:JsonPropertyName", "product_name");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity")
                        .HasAnnotation("Relational:JsonPropertyName", "quantity");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("supplier_name")
                        .HasAnnotation("Relational:JsonPropertyName", "supplier_name");

                    b.Property<string>("UserFullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_full_name")
                        .HasAnnotation("Relational:JsonPropertyName", "user_full_name");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("integer")
                        .HasColumnName("warehouse_id")
                        .HasAnnotation("Relational:JsonPropertyName", "warehouse_id");

                    b.HasKey("HistoryId")
                        .HasName("histories_pkey");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("histories", (string)null);
                });

            modelBuilder.Entity("WarehouseManagerServer.Models.Entities.Permission", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id")
                        .HasAnnotation("Relational:JsonPropertyName", "user_id");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("integer")
                        .HasColumnName("warehouse_id")
                        .HasAnnotation("Relational:JsonPropertyName", "warehouse_id");

                    b.Property<string[]>("UserPermissions")
                        .IsRequired()
                        .HasColumnType("varchar(6)[]")
                        .HasColumnName("user_permissions")
                        .HasAnnotation("Relational:JsonPropertyName", "user_permissions");

                    b.HasKey("UserId", "WarehouseId")
                        .HasName("permissions_pkey");

                    b.HasIndex("WarehouseId");

                    b.ToTable("permissions", (string)null);
                });

            modelBuilder.Entity("WarehouseManagerServer.Models.Entities.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("product_id")
                        .HasAnnotation("Relational:JsonPropertyName", "product_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProductId"));

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiry_date")
                        .HasAnnotation("Relational:JsonPropertyName", "expiry_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("quantity")
                        .HasAnnotation("Relational:JsonPropertyName", "quantity");

                    b.Property<int>("SupplierId")
                        .HasColumnType("integer")
                        .HasColumnName("supplier_id")
                        .HasAnnotation("Relational:JsonPropertyName", "supplier_id");

                    b.Property<decimal>("UnitPrice")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("unit_price")
                        .HasDefaultValueSql("1")
                        .HasAnnotation("Relational:JsonPropertyName", "unit_price");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("integer")
                        .HasColumnName("warehouse_id")
                        .HasAnnotation("Relational:JsonPropertyName", "warehouse_id");

                    b.HasKey("ProductId")
                        .HasName("products_pkey");

                    b.HasIndex("SupplierId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("WarehouseManagerServer.Models.Entities.RefreshToken", b =>
                {
                    b.Property<int>("TokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TokenId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("TokenId");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("WarehouseManagerServer.Models.Entities.Supplier", b =>
                {
                    b.Property<int>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("supplier_id")
                        .HasAnnotation("Relational:JsonPropertyName", "supplier_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SupplierId"));

                    b.Property<string>("ContactInfo")
                        .HasColumnType("text")
                        .HasColumnName("contact_info")
                        .HasAnnotation("Relational:JsonPropertyName", "contact_info");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("integer")
                        .HasColumnName("warehouse_id")
                        .HasAnnotation("Relational:JsonPropertyName", "warehouse_id");

                    b.HasKey("SupplierId")
                        .HasName("suppliers_pkey");

                    b.HasIndex("WarehouseId");

                    b.ToTable("suppliers", (string)null);
                });

            modelBuilder.Entity("WarehouseManagerServer.Models.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("user_id")
                        .HasAnnotation("Relational:JsonPropertyName", "user_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email")
                        .HasAnnotation("Relational:JsonPropertyName", "email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("fullname")
                        .HasAnnotation("Relational:JsonPropertyName", "full_name");

                    b.Property<DateTime>("JoinDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("join_date")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP")
                        .HasAnnotation("Relational:JsonPropertyName", "join_date");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.HasKey("UserId")
                        .HasName("users_pkey");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("WarehouseManagerServer.Models.Entities.Warehouse", b =>
                {
                    b.Property<int>("WarehouseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("warehouse_id")
                        .HasAnnotation("Relational:JsonPropertyName", "warehouse_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("WarehouseId"));

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP")
                        .HasAnnotation("Relational:JsonPropertyName", "create_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("name")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.HasKey("WarehouseId")
                        .HasName("warehouses_pkey");

                    b.ToTable("warehouses", (string)null);
                });

            modelBuilder.Entity("UserWarehouse", b =>
                {
                    b.HasOne("WarehouseManagerServer.Models.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UsersUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WarehouseManagerServer.Models.Entities.Warehouse", null)
                        .WithMany()
                        .HasForeignKey("WarehousesWarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WarehouseManagerServer.Models.Entities.History", b =>
                {
                    b.HasOne("WarehouseManagerServer.Models.Entities.Product", null)
                        .WithMany("Histories")
                        .HasForeignKey("ProductId");

                    b.HasOne("WarehouseManagerServer.Models.Entities.User", null)
                        .WithMany("Histories")
                        .HasForeignKey("UserId");

                    b.HasOne("WarehouseManagerServer.Models.Entities.Warehouse", "Warehouse")
                        .WithMany("Histories")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("history_warehouse_id_fkey");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("WarehouseManagerServer.Models.Entities.Permission", b =>
                {
                    b.HasOne("WarehouseManagerServer.Models.Entities.User", "User")
                        .WithMany("Permissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("permission_user_id_fkey");

                    b.HasOne("WarehouseManagerServer.Models.Entities.Warehouse", "Warehouse")
                        .WithMany("Permissions")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("permission_warehouse_id_fkey");

                    b.Navigation("User");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("WarehouseManagerServer.Models.Entities.Product", b =>
                {
                    b.HasOne("WarehouseManagerServer.Models.Entities.Supplier", "Supplier")
                        .WithMany("Products")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired()
                        .HasConstraintName("product_supplier_id_fkey");

                    b.HasOne("WarehouseManagerServer.Models.Entities.Warehouse", "Warehouse")
                        .WithMany("Products")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("product_warehouse_id_fkey");

                    b.Navigation("Supplier");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("WarehouseManagerServer.Models.Entities.RefreshToken", b =>
                {
                    b.HasOne("WarehouseManagerServer.Models.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WarehouseManagerServer.Models.Entities.Supplier", b =>
                {
                    b.HasOne("WarehouseManagerServer.Models.Entities.Warehouse", "Warehouse")
                        .WithMany("Suppliers")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("supplier_warehouse_id_fkey");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("WarehouseManagerServer.Models.Entities.Product", b =>
                {
                    b.Navigation("Histories");
                });

            modelBuilder.Entity("WarehouseManagerServer.Models.Entities.Supplier", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("WarehouseManagerServer.Models.Entities.User", b =>
                {
                    b.Navigation("Histories");

                    b.Navigation("Permissions");

                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("WarehouseManagerServer.Models.Entities.Warehouse", b =>
                {
                    b.Navigation("Histories");

                    b.Navigation("Permissions");

                    b.Navigation("Products");

                    b.Navigation("Suppliers");
                });
#pragma warning restore 612, 618
        }
    }
}
